### ISSUE TITLE
Include read_sas

### ISSUE THREAD

**Issue by jonathananolan** [grattan/grattandata#22]
Can I add read_sas as an import function where the filename contains sas7bdat until rio sorts itself out?

**Comment by MattCowgill** [comment]
I'm not sure what you mean. Do you mean you want `read_microdata()` to call `read_sas()` directly when a SAS file is requested, rather than calling import? If we do that, we should do it for `read_dta()` and Stata files too, because all `haven::read_*` functions gained the same new functionality (`col_select` etc)
